apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-number-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking-number-api
  template:
    metadata:
      labels:
        app: tracking-number-api
    spec:
      containers:
        - name: tracking-number-api
          image: your-dockerhub-username/tracking-number-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/teleport
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
