apiVersion: v1
kind: Service
metadata:
  name: tracking-number-service
spec:
  type: LoadBalancer
  selector:
    app: tracking-number-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
